name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  koyeb-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Koyeb CLI
        uses: koyeb/action-git-deploy@v1
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        with:
          app-name: "fishing-app"
          service-name: "express-server"
          service-ports: "3000:http"
          service-routes: "/:3000"
          service-env: "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}"
